# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CipherSuite',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('kex', models.CharField(max_length=20, verbose_name='Key exchange algorithm')),
                ('enc', models.CharField(max_length=20, verbose_name='Encryption algorithm')),
                ('mac', models.CharField(max_length=20, verbose_name='MAC algorithm')),
            ],
        ),
        migrations.CreateModel(
            name='Rfc',
            fields=[
                ('number', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ist', 'Internet Standard'), ('pst', 'Proposed Standard'), ('dst', 'Draft Standard'), ('bcp', 'Best Current Practise'), ('obs', 'Informational'), ('std', 'Experimental'), ('std', 'Historic')], max_length=3)),
                ('title', models.CharField(max_length=250)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('cipher_suites', models.ManyToManyField(blank=True, to='directory.CipherSuite', verbose_name='Defined cipher suites')),
                ('obsoleted_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obsoleted_set', to='directory.Rfc')),
                ('obsoletes', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obsoleting_set', to='directory.Rfc')),
            ],
        ),
        migrations.AddField(
            model_name='ciphersuite',
            name='rfcs',
            field=models.ManyToManyField(blank=True, to='directory.Rfc', verbose_name='Referring RFC'),
        ),
    ]
