# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciphersuite',
            name='gnutls_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='ciphersuite',
            name='openssl_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
