# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20170509_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciphersuite',
            name='prt',
            field=models.CharField(default='', editable=False, max_length=20, verbose_name='Protocol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ciphersuite',
            name='enc',
            field=models.CharField(editable=False, max_length=20, verbose_name='Encryption algorithm'),
        ),
        migrations.AlterField(
            model_name='ciphersuite',
            name='kex',
            field=models.CharField(editable=False, max_length=20, verbose_name='Key exchange algorithm'),
        ),
        migrations.AlterField(
            model_name='ciphersuite',
            name='mac',
            field=models.CharField(editable=False, max_length=20, verbose_name='MAC algorithm'),
        ),
    ]
