# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20170510_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortcode',
            fields=[
                ('short', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('long', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
