# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcode',
            name='long',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
