# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20171120_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='GnutlsCipher',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('hex_byte_1', models.CharField(max_length=4)),
                ('hex_byte_2', models.CharField(max_length=4)),
                ('tls_version', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'verbose_name': 'gnutls cipher',
                'verbose_name_plural': 'gnutls ciphers',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpensslCipher',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('hex_byte_1', models.CharField(max_length=4)),
                ('hex_byte_2', models.CharField(max_length=4)),
                ('tls_version', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'verbose_name': 'openssl cipher',
                'verbose_name_plural': 'openssl ciphers',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ciphersuite',
            name='tls_version',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='opensslcipher',
            unique_together=set([('hex_byte_1', 'hex_byte_2')]),
        ),
        migrations.AlterUniqueTogether(
            name='gnutlscipher',
            unique_together=set([('hex_byte_1', 'hex_byte_2')]),
        ),
    ]
