# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20170511_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcode',
            name='vulnerable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
