# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20171215_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciphersuite',
            name='tls_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gnutlscipher',
            name='tls_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='opensslcipher',
            name='tls_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
