# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_shortcode_vulnerable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortcode',
            old_name='vulnerable',
            new_name='is_vulnerable',
        ),
        migrations.AddField(
            model_name='shortcode',
            name='vulnerable_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
