# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20171217_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gnutlscipher',
            old_name='tls_version',
            new_name='min_tls_version',
        ),
        migrations.RenameField(
            model_name='opensslcipher',
            old_name='tls_version',
            new_name='min_tls_version',
        ),
        migrations.AlterField(
            model_name='ciphersuite',
            name='tls_version',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
