# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_auto_20170511_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncAlgorithm',
            fields=[
                ('short_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('long_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KexAlgorithm',
            fields=[
                ('short_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('long_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MacAlgorithm',
            fields=[
                ('short_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('long_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolVersion',
            fields=[
                ('short_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('long_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Shortcode',
        ),
        migrations.RemoveField(
            model_name='ciphersuite',
            name='enc',
        ),
        migrations.RemoveField(
            model_name='ciphersuite',
            name='kex',
        ),
        migrations.RemoveField(
            model_name='ciphersuite',
            name='mac',
        ),
        migrations.RemoveField(
            model_name='ciphersuite',
            name='prt',
        ),
        migrations.RemoveField(
            model_name='ciphersuite',
            name='rfcs',
        ),
        migrations.AddField(
            model_name='ciphersuite',
            name='related_rfcs',
            field=models.ManyToManyField(blank=True, to='directory.Rfc', verbose_name='Related RFC'),
        ),
        migrations.AlterField(
            model_name='rfc',
            name='obsoleted_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='obsoleted_set', to='directory.Rfc'),
        ),
        migrations.AlterField(
            model_name='rfc',
            name='obsoletes',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='obsoleting_set', to='directory.Rfc'),
        ),
        migrations.AddField(
            model_name='protocolversion',
            name='vulnerability',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='directory.Vulnerability'),
        ),
        migrations.AddField(
            model_name='macalgorithm',
            name='vulnerability',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='directory.Vulnerability'),
        ),
        migrations.AddField(
            model_name='kexalgorithm',
            name='vulnerability',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='directory.Vulnerability'),
        ),
        migrations.AddField(
            model_name='encalgorithm',
            name='vulnerability',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='directory.Vulnerability'),
        ),
        migrations.AddField(
            model_name='ciphersuite',
            name='enc_algorithm',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='directory.EncAlgorithm', verbose_name='Encryption algorithm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ciphersuite',
            name='kex_algorithm',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='directory.KexAlgorithm', verbose_name='Key exchange algorithm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ciphersuite',
            name='mac_algorithm',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='directory.MacAlgorithm', verbose_name='MAC algorithm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ciphersuite',
            name='protocol_version',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='directory.ProtocolVersion', verbose_name='Protocol version'),
            preserve_default=False,
        ),
    ]
