# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_auto_20170514_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciphersuite',
            name='related_rfcs',
            field=models.ManyToManyField(blank=True, null=True, to='directory.Rfc', verbose_name='Related RFC'),
        ),
    ]
