# Generated by Django 2.0.7 on 2018-07-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_auto_20180716_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='glyphicon',
            field=models.CharField(help_text='For reference, see https://getbootstrap.com/docs/3.3/components#glyphicons', max_length=50),
        ),
    ]
