# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_auto_20170515_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciphersuite',
            name='related_rfcs',
            field=models.ManyToManyField(blank=True, to='directory.Rfc', verbose_name='Related RFC'),
        ),
        migrations.AlterField(
            model_name='rfc',
            name='cipher_suites',
            field=models.ManyToManyField(blank=True, to='directory.CipherSuite', verbose_name='Defined cipher suites'),
        ),
    ]
