# Generated by Django 2.1 on 2018-10-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_auto_20181006_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlsversion',
            name='short',
            field=models.CharField(blank=True, editable=False, max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='tlsversion',
            unique_together={('major', 'minor')},
        ),
    ]
