# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_auto_20170515_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encalgorithm',
            name='vulnerability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.Vulnerability'),
        ),
        migrations.AlterField(
            model_name='kexalgorithm',
            name='vulnerability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.Vulnerability'),
        ),
        migrations.AlterField(
            model_name='macalgorithm',
            name='vulnerability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.Vulnerability'),
        ),
        migrations.AlterField(
            model_name='protocolversion',
            name='vulnerability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.Vulnerability'),
        ),
    ]
