# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_auto_20170515_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
