# Generated by Django 2.1.7 on 2019-02-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0014_auto_20181030_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciphersuite',
            name='name',
            field=models.CharField(db_index=True, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='severity',
            field=models.IntegerField(choices=[(2, 'High'), (1, 'Medium'), (0, 'Low')], default=0),
        ),
    ]
