# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0014_auto_20170515_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciphersuite',
            name='protocol_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.ProtocolVersion', verbose_name='Protocol version'),
        ),
    ]
