# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0019_auto_20170515_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='cve_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cvss_score',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rfc',
            name='defined_cipher_suites',
            field=models.ManyToManyField(blank=True, related_name='defining_rfcs', to='directory.CipherSuite', verbose_name='Defined cipher suites'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
